// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxt0pJs3S9PqUDAfMPePLGuWa86agMXgo',
    appId: '1:264923401330:web:a795fdf15ce1b82eefc6eb',
    messagingSenderId: '264923401330',
    projectId: 'startup-my-app',
    authDomain: 'startup-my-app.firebaseapp.com',
    databaseURL: 'https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'startup-my-app.appspot.com',
    measurementId: 'G-7XX9H6HB3T',
  );

  static const FirebaseOptions linux = FirebaseOptions(
      apiKey: "AIzaSyDxt0pJs3S9PqUDAfMPePLGuWa86agMXgo",
      authDomain: "startup-my-app.firebaseapp.com",
      databaseURL: "https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "startup-my-app",
      storageBucket: "startup-my-app.appspot.com",
      messagingSenderId: "264923401330",
      appId: "1:264923401330:web:bc2ac394fd20f9a6efc6eb",
      measurementId: "G-BYYRKGWLYH"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFrnwQVOSBpd_i3Z2gvPEDPToXGgsNYkg',
    appId: '1:264923401330:android:7a69d1051ea97f5aefc6eb',
    messagingSenderId: '264923401330',
    projectId: 'startup-my-app',
    databaseURL: 'https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'startup-my-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuLvvvcelbOLN4dcnrBdA7Iqrb1G17Xc',
    appId: '1:264923401330:ios:e8249ee623f577b8efc6eb',
    messagingSenderId: '264923401330',
    projectId: 'startup-my-app',
    databaseURL: 'https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'startup-my-app.appspot.com',
    iosClientId: '264923401330-o9iebtsbe3qhk50vdth89dj6r5c37d7t.apps.googleusercontent.com',
    iosBundleId: 'edu.anisiya.startup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHuLvvvcelbOLN4dcnrBdA7Iqrb1G17Xc',
    appId: '1:264923401330:ios:e8249ee623f577b8efc6eb',
    messagingSenderId: '264923401330',
    projectId: 'startup-my-app',
    databaseURL: 'https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'startup-my-app.appspot.com',
    iosClientId: '264923401330-o9iebtsbe3qhk50vdth89dj6r5c37d7t.apps.googleusercontent.com',
    iosBundleId: 'edu.anisiya.startup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxt0pJs3S9PqUDAfMPePLGuWa86agMXgo',
    appId: '1:264923401330:web:20c334f226cb400befc6eb',
    messagingSenderId: '264923401330',
    projectId: 'startup-my-app',
    authDomain: 'startup-my-app.firebaseapp.com',
    databaseURL: 'https://startup-my-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'startup-my-app.appspot.com',
    measurementId: 'G-DLPHBHV0XZ',
  );

}